```{r}
data <- matrix(c(
    6, 6, 18, 8, 11, 34, 28, 71, 43, 33, 20,
    27, 23, 64, 44, 30, 75, 26, 124, 54, 30, 14,
    25, 28, 36, 35, 15, 44, 42, 54, 34, 29, 39,
    15, 13, 22, 29, 31, 64, 30, 64, 56, 20, 21
), ncol = 4, byrow = FALSE)
```

```{r}
comLab <- data[, 1:2]
statLab <- data[, 3:4]
```

```{r}
D <- comLab - statLab
```

```{r}
n <- nrow(D)
p <- ncol(D)
alfa <- 0.05
```
```{r}
satu <- rep(1, n)
dbar <- 1 / n * t(D) %*% satu
```
```{r}
Sd <- cov(D)
```
```{r}
# Statistik Hitung
T2 <- n * t(dbar) %*% solve(Sd) %*% dbar
```
```{r}
# Statistik Uji
Ftabel <- qf(1 - alfa, p, n - p)
c2 <- (n - 1) * p / (n - p) * Ftabel
```
```{r}
if (T2 > c2) print("TOLAK H0") else print("GAGAL TOLAK H0")
# MINIMAL ADA SATU VARIABEL YANG BERBEDA
```
```{r}
# CEK CONFIDENCE INTERVAL - BANTUAN VEKTOR a
a.d1 <- c(1, 0)
a.d2 <- c(0, 1)
c <- sqrt(c2)
```
```{r}
# SCI
d1.LB <- t(a.d1) %*% dbar - c * sqrt(t(a.d1) %*% Sd %*% a.d1 / n)
d1.UB <- t(a.d1) %*% dbar + c * sqrt(t(a.d1) %*% Sd %*% a.d1 / n)
SCI.d1 <- c(d1.LB, d1.UB)

d2.LB <- t(a.d2) %*% dbar - c * sqrt(t(a.d2) %*% Sd %*% a.d2 / n)
d2.UB <- t(a.d2) %*% dbar + c * sqrt(t(a.d2) %*% Sd %*% a.d2 / n)
SCI.d2 <- c(d2.LB, d2.UB)
```

```{r}
# BCI
t.tabel <- qt(1 - alfa / (2 * p), n - 1)
d1.LB <- t(a.d1) %*% dbar - t.tabel * sqrt(t(a.d1) %*% Sd %*% a.d1 / n)
d1.UB <- t(a.d1) %*% dbar + t.tabel * sqrt(t(a.d1) %*% Sd %*% a.d1 / n)
BCI.d1 <- c(d1.LB, d1.UB)

d2.LB <- t(a.d2) %*% dbar - t.tabel * sqrt(t(a.d2) %*% Sd %*% a.d2 / n)
d2.UB <- t(a.d2) %*% dbar + t.tabel * sqrt(t(a.d2) %*% Sd %*% a.d2 / n)
BCI.d2 <- c(d2.LB, d2.UB)
```
